### ISSUE TITLE
Type error: Argument of type 'string | undefined' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by ALI-BOULHAJAT** [mep-agency/next-iubenda#11] opened 2024-05-22 09:50 UTC
Hello,

When I try to build my NextJs App with TS, it failed with this error
>
../../node_modules/@mep-agency/next-iubenda/src/components/ConsentAwareWrapper/index.tsx:105:23

Type error: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

   103 |
   104 |     if (useDefaultStyles === undefined || useDefaultStyles === true) {
   105 |       classNames.push(styles.wrapper);
   |_____________________^
   106 |}

**Comment by liarco** [comment] 2024-05-23 11:15
Hi @ALI-BOULHAJAT,
Unfortunately the provided info is not enough to troubleshoot your issue properly. I would suggest you to create a small GitHub repo with a reproducer (a minimal project that we can run and replicate the error) so we can take a look at it.

I also encourage you to take a look at our support policy: https://github.com/mep-agency#support-policy

Thank you.

**Comment by ALI-BOULHAJAT** [comment] 2024-05-23 11:46
Hello @liarco,

first thank you for your time, and for the issue, it's about types, some time the styles.wrapper can be undefined, and I think you need just more protection where you can check if styles.wrapper isn't undefined before push it to classNames.

thanks.

**Comment by liarco** [comment] 2024-05-23 12:14
Thanks for your follow-up @ALI-BOULHAJAT. Can you please explain to me in what scenario you think the value of `styles.wrapper` can actually be `undefined`? Because at first glance, I can't see any reasonable case where this should happen with a proper setup.

That's why I asked for a reproducer, I think you may have a broken setup or maybe your configuration falls into an edge case that I'm not aware of.

**Comment by ALI-BOULHAJAT** [comment] 2024-05-23 12:24
me too I don't see any reasonable case where this should happen, and also in dev mode I don't face this error, it's only when I try to build the whole project, and maybe it's only the TypeScript check, but it's stop all the build

**Comment by liarco** [comment] 2024-05-23 14:25
I did some tests with a couple of common setups we actively use (plain new NextJS projects with both regular and static build) but none of them has presented this issue. I'm sorry but unless you can provide us with the exact steps to reproduce the error I have to close this issue as it seems to be strongly related to your specific setup.

Please feel free to reply here if you have any additional info.

**Closed as completed by liarco** 2024-05-23 14:25 UTC
Labels: invalid

**Comment by ALI-BOULHAJAT** [comment] 2024-05-23 14:46
yes, I did test with a simple nextJs app project and it's work normally, maybe there is conflict with using a Monorepo, I will try to fix it, and then if it's something interesting I will share it with you.
thank you.

**Comment by liarco** [comment] 2024-05-23 14:53
You are welcome!

Just a quick info: our team mainly uses this tool in monorepos with [turbo](https://turbo.build/) and yarn/npm workspaces, so that use case should be supported too. I hope you can fix this soon.

**Comment by ALI-BOULHAJAT** [comment] 2024-05-24 12:08
Hello @liarco,

I believe I've identified the reason why you're not seeing the issue I'm facing, and why it may be occurring in my project but not a new, simple project.

It seems the root cause is that in my project's `tsconfig.json` file, I have the `"noUncheckedIndexedAccess"` option set to `true`. This is a TypeScript compiler setting that instructs the compiler to perform additional type-checking during the build process.

Specifically, with this option enabled, the compiler will verify that any access to an indexed property, such as `arr[i]` or `obj[key]`, is safe and won't result in a `TypeError` at runtime.

I'd recommend trying to add `"noUncheckedIndexedAccess": true` to the `compilerOptions` section of your own project's `tsconfig.json` file. Once you do this and try to build your application, you may start seeing the same error I'm experiencing.
